FROM multical_more_bags_web_base

RUN cd / && \
	git clone https://github.com/Luxcoldury/multical-web.git

RUN bash -c "cd /multical-web && source /multical-web-env/bin/activate && pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple"

RUN	chmod +x /multical-web/docker_entrypoint.sh

CMD ["/bin/bash", "/multical-web/docker_entrypoint.sh"]